const fs = require("fs");
const HtmlWebpackPlugin = require("html-webpack-plugin");

// Includes
const head = fs.readFileSync("src/includes/head.html");
const sectionHeader = fs.readFileSync("src/includes/section-header.html");
const sectionFooter = fs.readFileSync("src/includes/section-footer.html");
const breadcrumbs = fs.readFileSync("src/includes/breadcrumbs.html");
const productFilter = fs.readFileSync("src/includes/product-filter.html");
const sorting = fs.readFileSync("src/includes/sorting.html");
const pagination = fs.readFileSync("src/includes/pagination.html");
const temp = fs.readFileSync("src/includes/temp.html");

// Pages
module.exports = [
    new HtmlWebpackPlugin({
        template: "./src/index.html",
        filename: "index.html",
        inject: "body",
        title: "Dom Decor - Главная",
        head,
        sectionHeader,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/catalog.html",
        filename: "catalog.html",
        inject: "body",
        title: "Dom Decor - Каталог",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/download.html",
        filename: "download.html",
        inject: "body",
        title: "Dom Decor - Загрузки",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/contacts.html",
        filename: "contacts.html",
        inject: "body",
        title: "Dom Decor - Контакты",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/register.html",
        filename: "register.html",
        inject: "body",
        title: "Dom Decor - Регистрация",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/registerUser.html",
        filename: "registerUser.html",
        inject: "body",
        title: "Dom Decor - Регистрация пользователя",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/registerComp.html",
        filename: "registerComp.html",
        inject: "body",
        title: "Dom Decor - Регистрация компании",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/login.html",
        filename: "login.html",
        inject: "body",
        title: "Dom Decor - Логин",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkBasket.html",
        filename: "lkBasket.html",
        inject: "body",
        title: "Dom Decor - Корзина",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkBasketProducts.html",
        filename: "lkBasketProducts.html",
        inject: "body",
        title: "Dom Decor - Корзина",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkBasketAccepted.html",
        filename: "lkBasketAccepted.html",
        inject: "body",
        title: "Dom Decor - Спасибо за заказ",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkProjects.html",
        filename: "lkProjects.html",
        inject: "body",
        title: "Dom Decor - Мои проекты",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkProjects2.html",
        filename: "lkProjects2.html",
        inject: "body",
        title: "Dom Decor - Мои проекты",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkProjectsArchive.html",
        filename: "lkProjectsArchive.html",
        inject: "body",
        title: "Dom Decor - Мои проекты",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkProjectsPage.html",
        filename: "lkProjectsPage.html",
        inject: "body",
        title: "Dom Decor - Мои проекты",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkProjectsRoom.html",
        filename: "lkProjectsRoom.html",
        inject: "body",
        title: "Dom Decor - Комната проекта",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrders.html",
        filename: "lkOrders.html",
        inject: "body",
        title: "Dom Decor - Мои заказы",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrdering.html",
        filename: "lkOrdering.html",
        inject: "body",
        title: "Dom Decor - Страница заказа",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrderingCompany.html",
        filename: "lkOrderingCompany.html",
        inject: "body",
        title: "Dom Decor - Страница заказа компании",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrderingPickup.html",
        filename: "lkOrderingPickup.html",
        inject: "body",
        title: "Dom Decor - Самовывоз",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/brands.html",
        filename: "brands.html",
        inject: "body",
        title: "Dom Decor - Бренды",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrdersProjects.html",
        filename: "lkOrdersProjects.html",
        inject: "body",
        title: "Dom Decor - Мои заказы",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrdersProjectPage.html",
        filename: "lkOrdersProjectPage.html",
        inject: "body",
        title: "Dom Decor - Мои заказы",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrdersPayment.html",
        filename: "lkOrdersPayment.html",
        inject: "body",
        title: "Dom Decor - Мои заказы",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkOrdersPaid.html",
        filename: "lkOrdersPaid.html",
        inject: "body",
        title: "Dom Decor - Мои заказы",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkData.html",
        filename: "lkData.html",
        inject: "body",
        title: "Dom Decor - Личные данные",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkDataCompany.html",
        filename: "lkDataCompany.html",
        inject: "body",
        title: "Dom Decor - Личные данные компании",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/oferta.html",
        filename: "oferta.html",
        inject: "body",
        title: "Dom Decor - Бонусная программа",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkRestore.html",
        filename: "lkRestore.html",
        inject: "body",
        title: "Dom Decor - Восстановление доступа",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkPassReset.html",
        filename: "lkPassReset.html",
        inject: "body",
        title: "Dom Decor - Восстановление доступа",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkPassResetAccept.html",
        filename: "lkPassResetAccept.html",
        inject: "body",
        title: "Dom Decor - Восстановление доступа",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/lkPassResetEmail.html",
        filename: "lkPassResetEmail.html",
        inject: "body",
        title: "Dom Decor - Восстановление доступа",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/services.html",
        filename: "services.html",
        inject: "body",
        title: "Dom Decor - Услуги",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/servicesTrans.html",
        filename: "servicesTrans.html",
        inject: "body",
        title: "Dom Decor - Услуги - Доставка",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/servicesColer.html",
        filename: "servicesColer.html",
        inject: "body",
        title: "Dom Decor - Услуги - Колеровка",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/productPage.html",
        filename: "productPage.html",
        inject: "body",
        title: "Dom Decor - Карточка товара",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/about.html",
        filename: "about.html",
        inject: "body",
        title: "О компании",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/about-professional.html",
        filename: "about-professional.html",
        inject: "body",
        title: "Профессионалы",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/about-physical.html",
        filename: "about-physical.html",
        inject: "body",
        title: "Физлица",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/about-dealer.html",
        filename: "about-dealer.html",
        inject: "body",
        title: "Диллеры",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/blog.html",
        filename: "blog.html",
        inject: "body",
        title: "Блог | Dom Decor",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/gallery.html",
        filename: "gallery.html",
        inject: "body",
        title: "Галерея проектов",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/blogItem.html",
        filename: "blogItem.html",
        inject: "body",
        title: "Блог - статья",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/blogItemSlider.html",
        filename: "blogItemSlider.html",
        inject: "body",
        title: "Блог - статья",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/blogArticle.html",
        filename: "blogArticle.html",
        inject: "body",
        title: "Блог - статья",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/steps.html",
        filename: "steps.html",
        inject: "body",
        title: "Комплектация объектов",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/blogVideo.html",
        filename: "blogVideo.html",
        inject: "body",
        title: "Блог - Видео",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/servicesSize.html",
        filename: "servicesSize.html",
        inject: "body",
        title: "Услуги - Замеры",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/servicesVideo.html",
        filename: "servicesVideo.html",
        inject: "body",
        title: "Услуги - Видео",
        head,
        sectionHeader,
        breadcrumbs,
        productFilter,
        sorting,
        pagination,
        sectionFooter,
        temp,
    }),
    new HtmlWebpackPlugin({
        template: "./src/pages/404.html",
        filename: "404.html",
        inject: "body",
        title: "404",
        head,
        sectionHeader,
        productFilter,
        sectionFooter,
        temp,
    }),
];
